# Generated by Django 4.2.6 on 2023-12-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=7000)),
                ('img1', models.ImageField(default='home.jpg', upload_to='homepage')),
                ('img2', models.ImageField(default='home.jpg', upload_to='homepage')),
                ('img3', models.ImageField(default='home.jpg', upload_to='homepage')),
            ],
        ),
    ]
