# Generated by Django 4.2.6 on 2023-12-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=7000)),
                ('img1', models.ImageField(default='services.jpg', upload_to='servicespage')),
                ('img2', models.ImageField(default='services.jpg', upload_to='servicespage')),
                ('img3', models.ImageField(default='services.jpg', upload_to='servicespage')),
                ('img4', models.ImageField(default='services.jpg', upload_to='servicespage')),
            ],
        ),
    ]
