# Generated by Django 3.2.23 on 2023-12-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('travel_date', models.CharField(blank=True, max_length=100)),
                ('return_date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
