# Generated by Django 4.2.6 on 2023-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=7000)),
                ('img1', models.ImageField(default='test.jpg', upload_to='test')),
                ('img2', models.ImageField(default='test.jpg', upload_to='test')),
                ('img3', models.ImageField(default='test.jpg', upload_to='test')),
            ],
        ),
    ]
